#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is part of kubawerlos/php-cs-fixer-config.
 *
 * (c) 2020 Kuba Werłos
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php'] as $autoload) {
    if (file_exists($autoload)) {
        require_once $autoload;
        break;
    }
}

use PhpCsFixerConfig\FixInit;

try {
    (new FixInit())->init(getcwd());
} catch (RuntimeException $exception) {
    echo $exception->getMessage(), PHP_EOL;
    exit(1);
}
